import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Header from "./components/header/header";
import { UserProvider } from "./components/context/user-context";
import { RecordProvider } from "./components/context/userRecord-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <UserProvider>
          <RecordProvider>
            {children}
            <ToastContainer />
          </RecordProvider>
        </UserProvider>
      </body>
    </html>
  );
}
