// "use client";
import { Inter } from "next/font/google";
// import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Header from "../components/header/header";
import { UserProvider } from "../components/context/user-context";
// import { useRouter } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });
// const router = useRouter();

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const logout = () => {
//   localStorage.removeItem("token");
//   router.push("/login");
// };

export default function MainLayout({ children }) {
  return (
    <>
      <UserProvider>
        <Header
        // logout={logout}
        />
        {children}
      </UserProvider>
    </>
  );
}
